### PR TITLE
makefile: call pkg-config only during initialization

### PR DESCRIPTION
**Pull request by ra1nb0w**
- add gitignore to simplify test and commit management
- makefile: call pkg-config only during variable initialisation and not each compile command

I thing that we can also merge the two Makefile or move to cmake.

### CODE REVIEW

**Review by dl1ycf — COMMENTED** [review]
Shouldn't .gitignore be a local file, that the user can adjust without going into the repo?

In my .gitignore, I do not have .idea, tmp, and build but I do have GNUmakefile, hpsdrsim, hpsdr.png etc.

My opinion is a) this file is important b) it should be outside the repo.

**Review by dl1ycf — APPROVED** [review]
This is a good idea. I shall merge this manually since I do not want to add .gitignore.

**Comment by ra1nb0w** [comment]
[gitignore](https://linux.die.net/man/5/gitignore) **must** be in the repository. Then you can add GNUmakefile, hpsdrsim, hpsdr.png and other files.

**Comment by dl1ycf** [comment]
I have applied the Makefile.mac change manually. Please check if I did it error-free (works for me).

**Pull request closed without merging**
