### PR TITLE
Noise: fix build issue

### PR DESCRIPTION
**Pull request by ra1nb0w**
remain a linking issue that I need to investigate since I can't find why it doesn't find the symbol.
Tested on Linux.

### CODE REVIEW

**Comment by ra1nb0w** [comment]
The linking issue was due to the need of vu3rdd's rnnoise so nothing related to pihpsdr.
Regarding Makefile: you need `pkg-config` of `libspecbleach` and `rnnoise` because it is not linked on vu3rdd's rnnoise .

**Comment by dl1ycf** [comment]
Dear David,

I have applied your first correction manually. For the second, my idea was that if there is a locally modified version of WDSP, then when creating the shared library (dylib) the link references are embedded there. E.g. there is no fftw linking in pihpsdr although WDSP is using it. 
So can you explain why a library not used by pihpsdr directly need be included in the Makefile?

**Comment by ra1nb0w** [comment]
first, thank you very much for your hard work!

The line `ifeq ($(EXTENDED_NOISE_REDUCTION_OPTIONS), EXTNR)` is to make the option equal to the others. Regarding the linking of `libspecbleach` and `rnnoise`, they are needed because upstream vu3rdd's wdsp are not linking it correctly and this is a temporary fix. I would like to open an issue at vu3rdd repository but it seems not in sync with your dsp code and I am not sure it is still maintained. It is a way to use those features without headache meanwhile the wdsp fork is up to date and fixed.

**Comment by dl1ycf** [comment]
I am in contact with vu3rdd, and he asked me where to find the latest WDSP code. So there is hope 
the WDSP there will be updated. I already exchanged comments on how this is internally included
in WDSP. I think the proper way is not to modify piHPSDR but download the vu3rdd wdsp if you 
want to use it and modify the makefile there. Note vu3rdd also had to modify the pihpsdr
makefile as to link with fftw3, and I think for the same reason.

**Comment by ra1nb0w** [comment]
Thank you. vu3rdd should modify his `Makefile` and fix the linking issue.
I close this PR.

**Pull request closed without merging**
