### PR TITLE
midi: add support for store/recall memory slots

### PR DESCRIPTION
**Pull request by ra1nb0w**
adds the following actions:

STOREM0:             store current VFO frequency on memory slot 0
STOREM1:             store current VFO frequency on memory slot 1
STOREM2:             store current VFO frequency on memory slot 2
STOREM3:             store current VFO frequency on memory slot 3
STOREM4:             store current VFO frequency on memory slot 4
RECALLM0:            load memory slot 0 in the current VFO
RECALLM1:            load memory slot 1 in the current VFO
RECALLM2:            load memory slot 2 in the current VFO
RECALLM3:            load memory slot 3 in the current VFO
RECALLM4:            load memory slot 4 in the current VFO

### CODE REVIEW

**Comment by dl1ycf** [comment]
The whole "store" menu seems to be deprecated since it is inactive (there is actually no button for this in the GUI: 
the calling sequence in new_menu.c is store_menu() <== start_store() <== store_cb() but the latter is an orphan.

Since this feature is not in the GUI why should it be in MIDI? Furthermore, it probably lacks maintenance since it
has not been used for some time.

These are the reasons why I would prefer *not* do add MIDI support.

**Comment by ra1nb0w** [comment]
I have the button in the interface
Screenshot 2020-10-10 at 20 13 29

what do you mean with "it is inactive"?

**Comment by dl1ycf** [comment]
Sorry, I have followed it from new_menu. I shall look at this again.

**Comment by dl1ycf** [comment]
I have to check and possibly clean up the memory code first,
it looks quite suspicious to me that vfo_band_changed() is
commented out in recall_select_cb() but this is necessary
to get antenna switching (and all those things which
possibly have to be done upon a band change) done.

Probably the „vfo band change“ needs to be moved up BEFORE
one restores mode and filter, since  band change normally
switches to the mode last used on that band, and then the
filter (and noise reduction, equalizer settings etc.) associated
with that mode are set. The the logical sequence of events is

- determine band from new frequency
- to the band change and set the frequency
- set mode
- set filter

and then one gets the noise reduction, noise blanker, and equalizer
settings associated with the mode. I also consider to store these
settings in the memory as well, and apply these settings without
storing them with the mode.

Do you find it logical to go back also to the noise and equalizer
settings active when the „store“ took place?

**Comment by ra1nb0w** [comment]
Good question. I think it depends on how we use the memory. I mean, if we switch between slots in a short time having noise and equaliser settings can be a very nice feature since the EMI remains quite the same. In long term (which is for me multiple days) is in antithesis with this reasoning.
Personally, I always use this feature in short term therefore maintaining "all" settings can enhance the user experience.

**Comment by dl1ycf** [comment]
For example, I am always using USB/LSB for SSB and DIGU for digimodes.
In SSB I have an equalizer „on“ and a 2.7 kHz filter, while in DIGU
I have no equalizer and a 3.3 kHz filter.

When switching between SSB and digimode, it is sufficient for me
to switch between USB/LSB and DIGU, and all the noise reduction and
equalizer settings are changed to the last setting with that mode
(that is, to the last setting change performed by the menus).

I find this absolutely necessary (otherwise it would make no sense to
have DIGU besides USB).

Furthermore, if you change band, you end up in the most-recently
used bandstack entry, and this includes the mode and filter settings.

Currently in the MEM feature, what is stored is the frequency, the filter
and the mode. So I suspect  recalling a memory
slot should be equivalent to the following sequence of events:

a) change the frequency to the new frequency, including a band change
   if new frequency is in another band

b) set mode to the new mode

c) set filter to the new filter

The order is of utmost importance since a) will change mode and that will 
in turn change filter, noise reduction and EQ settings,

THEN, change to the new mode (this will probably again change the filter
setting),

THEN change to the new filter setting.

The last should NOT change the filter setting stored with the mode.

This is so far not associated with MIDI, it is the question how the menu should
behave.

As to the MIDI implementation, I think it is not a good idea to call a GTK
callback function from the MIDI layer. I think I will put all the „work“
out of the callback functions into new functions and call these
from MIDI indirectly via new functions in ext.c.

Since MIDI runs completely asynchronously to the GUI, it is better to 
put all actions into the GTK idle queue otherwise you have to watch
out for thread safety, and GTK itself is not thread-safe.

**Comment by ra1nb0w** [comment]
You are right. The memory must store the mode/filter.

> As to the MIDI implementation, I think it is not a good idea to call a GTK callback function from the MIDI layer.

Yes. I did so to simplify the change but it should be moved to a standalone function.

**Pull request closed without merging**
