### PR TITLE
added multifunction encoder

### PR DESCRIPTION
**Pull request by laurencebarker**
Added a multifunction encoder, with (currently) fixed list of 28 possible actions. action displayed on VFO bar if window width is 1024 pixels

### CODE REVIEW

**Comment by dl1ycf** [comment]
I shall merge the pull request and then review. Pull requests that consists of more than 1 commit are somewhat more difficult to handle

**Comment by dl1ycf** [comment]
... had to add #include actions.h in vfo.c to make it compile ...

**Comment by bluzee** [comment]
M=AFGAIN is lit up in yellow on the VFO bar despite having no MIDI devices attached or configured.

**Comment by dl1ycf** [comment]
This will be corrected, I merged in the first attempt.
There will be an additional action NONE which is the
default and which will not cause anything printed.

**Comment by bluzee** [comment]
I understand.  

What midi devices are you finding to work with this?  Other than DJ controllers I'm not finding much else that looks like a good option.  A single deck controller would fit on my desk but I'm not finding any still in production. Behringer had a CMD PL-1 unit but that appears to be discontinued.

**Comment by dl1ycf** [comment]
I have a "Behringer CMD PL-1" which is no longer on the market.
But there are other such controllers from Behringer, and also
from Hercules.

The next option is to have a small Leonardo uC from the Arduino
familiy and build a controller according to the needs one has.
It is easy to let the Leonardo show up as  MIDI device (an
example is in the Manual). You can then also add CW features.

**Pull request merged**
