### PR TITLE
layout and style data load from files, css and json, i.s.o. hard coded

### PR DESCRIPTION
**Pull request by wwortel**
Layout and theme details are hard coded and require recompilation to see the effect of changes.
This patch loads settings for VFO layout, css, and settings used in cairo drawing from files.
Effects of changes to the configuration are visible upon restart of pihpsdr.
A directory 'config' was added. It's contents are to be put in the /home/pi/.config/pihpsdr/
working directory. No changes were made to the current layout choices.
Tested on amd64 and arm64. Installation of the libcjson-dev package is required.
The test for a negative layout width was replaced by defining the number of layouts in the json data.

### CODE REVIEW

**Comment by wwortel** [comment]
(For documentation purposes)
Annex 
Adapting the look of the screen to personal preferences.

The Graphical User Interface is made using Gtk widget definitions for things like buttons and boxes, and canvas areas to draw things like the filter and meter gauges.
Gtk takes its definitions for themed widgets from the file 'default.css' where they are in the format of cascaded style sheet definitions.
For drawing things like the S meter 'cairo' statements are used. It requires definitions for style, like the font for text and selections of line thicknesses and font sizes, and colour definitions. To draw the vfo area with its dials and 'led's to signal the status of the system, a series of x and y coordinates are required.
The reside in the file 'vfo_layout.json'.
All the data in 'vfo_layout.json' come in sets that form layouts that are adapted to various screen sizes, from a screen width of 640 pixels up to 1024. 
Additional layouts can be added if one wants to change the placing and looks of elements withing the VFO area, up to 10 layouts.
The file starts with defining the number of layouts present, followed by a version number of the file format used, followed by key names for each of the layouts present.
The order of layouts in the file matters as the layouts follow the order of fitting a larger screen width towards fitting smaller widths.
Adding a layout is a matter of increasing the number key value, adding a "nrN" : "<layout name>" entry in the right position, and adding that layout, with all its key-value pairs defined.  
The files 'default.css' and 'vfo_layout.json' are intended to be present in the working directory, which on a Raspberry or Linux PC will be in '~/.config/pihpsdr/', with the ~ indicating the home directory of the user, in our case user 'pi'.
The format number's unit and decimal digits are for backward compatible versions, i.e. no key:value pairs have been removed or repurposed. For changes that require change of pihpsdr's source code, a higher hundreds number is to be given. 
Notes:
Care is needed when editing any of these files. The checking of validity of the files by pihpsdr is limited and a typo or inconsistency will result in the programme not starting, probably without a warning message that would give guidance. More informative will be the standard output to the log file, also in the working directory. Successful loading of the files is explicitely logged and to some extent the detection of errors. Before editing anything, make a backup!
Note in the json file that in 'key : value' pairs the double quotes are quite important. The keys will be always "<string>" looking. The values can be a string, with double quotes, or a number without double quotes. Pihpsdr expects a certain type for the values and will not accept a string when a number is expected, and v.v.
For consistency of the entire GUI one may have to make changes in more than one file. An example is changing the text font chosen.
For use by Gtk, e.g. for button texts, it is defined in the default.css file. For use by cairo for adding text in drawing areas it is defind in 'vfo_layout.json'.

Tip: fonts that improve distinction between the digit zero and the letter O are a.o. Inconsolata and RobotoMono. They can be downloaded for free from the Internet.
E.g. for RobotoMono make the directory in Linux /usr/share/fonts/truetype/robotomono and unzip the font file into it. Adapt the relevant lines in 'default.css' and 'cairo_layout.json'.

**Comment by dl1ycf** [comment]
Everything that contain json is too complicated for me so I won't integrate that.
For me it is not worth the effort.

As to CSS:
I certainly want to keep the dependence of piHPSDR on
external files to a bare minium. This is why I made a change to WDSP (now taken over in the main version) to have
no longer a dependence on the "calculus" file. Likewise, I shall not allow a dependence on a CSS file.

So for load_css() to be acceptable, the MINIMUM requirement is that is inserts compile-time defaults if
no file has been found.

Together, this makes me "close with comment". I shall consider loading CSS from default locations, but this
will then be moved inside load_css whose interface should not change.

**Comment by dl1ycf** [comment]
P.S. : From your contribution, I added that load_css now first tries to load from "default.css" and only if
this fails, it takes the hard-wired data. Does this work for you?

**Comment by wwortel** [comment]
Closing a pull request before even the beginning of discussion is not exactly encouraging to a collective effort.
Substantial thought and time went into this pull request and I actually just finished an update that further enhances flexibility in the layout, yet maintaining 100% the current layout as one of the options.
It won't surprise you that I do not like the looks of pihpsdr, particularly not on a larger screen and in combination with a high-end sdr.
Just changing css is inadequate, because it only governs a small part of the looks, and none of control over what is shown and where in the VFO area.
As nearly no radio amateurs will embark upon compiling anything, providing a configuration file is a good way to let people use their creativity and implement their preferences.
Indeed it is a good idea, for reliability sake, to embed default versions of the layout data as part of the code, loaded when external ones are not found, or not load properly. The json argument amazed me in relation to the complexity of this pihpsdr/wdsp code in general.
It is just a C library and in the pull request there is a nicely working implementation ready to go and full of error checking and logging at all stages.
Coming back to my first sentence here. You write also "For me it is not worth the effort." I started from the idea that one does produce code here that is useful for others. For me it was worth the effort, as I like my current version much better than the standard one. But I do not want to go in a discussion about what should go where and with what looks in a hard coded fashion like it is now. Central to the pull request is allowing others to have that same freedom to adapt things to their liking without having to compile code. The pull request I have made such that one can alter things one does not like, while not forcing anything upon anybody.

**Comment by dl1ycf** [comment]
Note the "rule of x": a feature that will be used by x percent of the users must not cause more than x percent in the
software maintanance on the long run. If you look at software projects on a longer time scale, you will learn that "over-featuring" has a tendency to kill programs. THIS fork of piHPSDR is devoted to being kept simple. If you do not like this,
the beauty of open source is that you can fork your own branch and do whatever you want with this.

I may change my mind in the future, but at the moment the amount of code change, and the number of possible things that can go wrong, have triggered a decision to close the PR.

**Pull request closed without merging**
